### ISSUE TITLE
Metadata for "Playing" is not fully updated

### ISSUE THREAD

**Issue by udochrist** [Zefau/ioBroker.plex#11]
i have played in Succession on the Same Device:
- a Movie that is part of a "Collection" in Plex
- an Episode from a TV Show.

Looking at the Metadata displayed in iobroker I see that the media is shown as the TV Show ep, the collection is however still that of the movie played earlier.
I think some of the fields are not cleaned/updated when a new item gets played.

**Comment by Zefau** [comment]
Which adapter version are you on? What's your Node.js version? Are you using Plex Pass? Are you using Tautulli Webhook? 

Could you set the instance to debug and provide the log of playing both the items? 
Which are the fields / states which are not updated?

**Comment by udochrist** [comment]
Hi Zefau,
thanks for picking this up. i'm using the plexpass setup with version 0.60 of the adapter. Node is 10.6.2, iobroker 1.5.14 if i understand the versioning correct.

i don't know how to enable debug logging on the plex.0 instance, but i don't like posting logfiles anyway. i've stopped and started the adapter to remove all _playing entries (this is enabled at my end), played a movie belonging to a collection "The Cornetto Trilogy", ended the movie, marked it played and played a tv ep from NCIS LA. All on a web browser.

here are screenshots of the iobrokers objects:
**Movie started**
![Movie started](https://user-images.githubusercontent.com/869637/65390612-21ca8f00-dd61-11e9-8e52-abebdfffcf84.png)

**Movie stopped and marked watched.**
 (NB:with stopping i would actually have expected the _playing vars to empty out.)
![Movie stopped](https://user-images.githubusercontent.com/869637/65390623-47579880-dd61-11e9-8994-49140d38917c.png)

**Playing the TV ep.**
 (You can see that the collection is still from the movie, while the grandparenttitle shows the correct show name)
![tv ep started](https://user-images.githubusercontent.com/869637/65390636-7706a080-dd61-11e9-846e-2d86c7f7c1b5.png)

cheers

**Comment by Zefau** [comment]
Sorry for the delay. I have been working on this today and will provide an update next week.

**Comment by Zefau** [comment]
@udochrist Sorry again for the delay. Could you try and install v0.7.0 from Github? This should address this bug.
```
iobroker url https://github.com/Zefau/ioBroker.plex
```

**Comment by udochrist** [comment]
tested it.

issue is still the same for the same use case. i also did the test vice versa and switched from a tv episode to a movie and the same issue is with i.e. the grandParentXYZ fields.

the log now shows some more warnings however

```

plex.0 | 2019-10-17 21:58:38.000 | warn | (3142) library.runGarbageCollector is not a function
plex.0 | 2019-10-17 21:58:28.604 | warn | (3142) library.runGarbageCollector is not a function
plex.0 | 2019-10-17 21:58:04.576 | warn | (3142) library.runGarbageCollector is not a function
plex.0 | 2019-10-17 21:57:42.235 | warn | (3142) library.runGarbageCollector is not a function
plex.0 | 2019-10-17 21:57:01.455 | warn | (3142) library.runGarbageCollector is not a function
plex.0 | 2019-10-17 21:56:55.051 | warn | (3142) library.runGarbageCollector is not a function
plex.0 | 2019-10-17 21:56:23.577 | warn | (3142) library.runGarbageCollector is not a function
plex.0 | 2019-10-17 21:56:20.409 | warn | (3142) library.runGarbageCollector is not a function

```

**Comment by Zefau** [comment]
Sorry, forgot to update the library, which actually provides the function `library.runGarbageCollector`. Could you update from Github once more? Thanks

**Comment by udochrist** [comment]
warnings are gone, but issue is not fully fixed. 
from the original test case the collection is now no longer populated. this is correct.
however switching from a tv ep to a movie still keeps the grandParentXYZ fields from the tv ep.

**Comment by udochrist** [comment]
BTW: since the last update i get quite some logs complainig about "undefined"
```
plex.0 | 2019-10-22 08:18:03.076 | warn | (872) Cannot read property '_playing.udosipadpro2-<GUID>' of undefined
plex.0 | 2019-10-22 08:18:02.637 | warn | (872) Cannot read property '_playing.udosipadpro2-<GUID>' of undefined
plex.0 | 2019-10-22 08:17:51.946 | warn | (872) Cannot read property '_playing.udosipadpro2-<GUID>' of undefined
```

**Comment by Zefau** [comment]
Please check out `v0.8.0` if this release solves this issue now completely. Thanks.

**Comment by udochrist** [comment]
Hi. Excellent work. Metadata is now fully matching the played item (tested tv, music and movie switching). Plus there are no more warnings in the log.
