### ISSUE TITLE
Number of playing streams?

### ISSUE THREAD

**Issue by dragon299** [Zefau/ioBroker.plex#14]
Is there a possiblity to read the number of currently playing streams using this adapter?

Sry for this stupid question I am not able to find a state which gives me this number.

**Comment by Zefau** [comment]
Which version are you on?
The state `plex.0._playing.playing` (`Players currently playing`) holds the current players playing.

What information are you looking for? Probably no effort to add it.

**Comment by dragon299** [comment]
Thanks for your fast answer. Looks like this (plex.0._playing.playing) is exactly the state I am looking for. Unfortunately it is missing in my environment. 

Please find attached a screenshot:
![image](https://user-images.githubusercontent.com/2734035/66978082-c3b37200-f0a8-11e9-8908-4f66445d12a5.png)

I run version 0.3.1 currently.

**Comment by Zefau** [comment]
Try the version from the latest repository.

**Comment by dragon299** [comment]
The newest version gives me the mentioned state. Unfortunately it is not exactly what I am looking for. I need a state which gives me the number (Integer) of concurrent streams running at the moment.

In plex.0._playing.playing I see only the devices/players currently streaming. I tought I could count those devices with a little script but that does not work, because if there a multiply streams from the same device (sample chrome), I will have only one entry. 

Would it be possibly to add such a state to this adapter?

Thank you for your efforts.

**Comment by Zefau** [comment]
I could add that, but how do you have multiple streams from the same device? I thought it is only possible to have one stream per device at a moment?

**Comment by dragon299** [comment]
You can watch multiple streams if you start plex in multiple chrome tabs. Of course this is not a really common task but you could have 2 different users, which watch something in paralell on two different pc´s using chrome.

**Comment by Zefau** [comment]
That's true. I will implement the number of concurrent streams with one of the next releases.

**Comment by Zefau** [comment]
Please check out v0.8.0 if the newly added state `streams` does fit your needs. Thanks

**Comment by dragon299** [comment]
Looks like there is a bug in v0.8.0. The adapter is not able to start in my environment. Please find attached the error message:

> error by controller[0]: at Adapter.ready (/opt/iobroker/node_modules/iobroker.plex/plex.js:90:32)
> error by controller[0]: TypeError: Cannot read property 'forEach' of undefined

**Comment by Zefau** [comment]
Sorry. Could you try version `v0.8.1` from Github?

**Comment by dragon299** [comment]
thanks a lot, the new version works perfectly and the new "streams" state is exactly what I was looking for.

**Comment by Zefau** [comment]
Thanks a lot for your donation and support!
