### ISSUE TITLE
datenpunkt type änderung

### ISSUE THREAD

**Issue by liv-in-sky** [Zefau/ioBroker.plex#15]
hallo zefau - ich versuche gerade ein script zu schreiben, welches die datenpunkte etwas analysiert und auswertet  - dabei ist aufgefallen , dass du im adapter datenpunkte vom type text und double hast - man sagte mir, ich solle ein issue dazu erstellen 
im forum: https://forum.iobroker.net/post/312375

![Image 4](https://user-images.githubusercontent.com/18462890/67006419-60940080-f0e5-11e9-8dfb-0ce3061becf4.png)

![Image 3](https://user-images.githubusercontent.com/18462890/67006463-7e616580-f0e5-11e9-8597-9ee27e0280a4.png)

gruß

**Comment by Zefau** [comment]
Kann ich bestätigen. Der Adapter übernimmt den Datentyp aus der API.
Was genau ist das Problem? Nur die Kombination von role `text` und type `double`?

Ich habe eine Anpassung in der Zeile 871 vorgenommen: `entry['type']` habe ich auf `string` geändert.
Von:
https://github.com/Zefau/ioBroker.plex/blob/49a1c91236881c11d5600908237f0cf53d26cc94/plex.js#L871

auf:

```
'type': entry['type'] == 'bool' ? 'boolean' : (entry['type'] == 'int' ? 'number' : 'string'),
```

**Comment by Zefau** [comment]
v0.7.0 auf Github behebt das Problem. Bestehende Objekte müssen vorher allerdings entfernt werden, damit diese durch den Adapter neu und korrekt angelegt werden.

**Comment by liv-in-sky** [comment]
super danke dir - ich lass mein script nochmal drüber laufen und gebe dir bescheid

**Comment by Zefau** [comment]
@liv-in-sky Wie sieht's aus? Passt's?

**Comment by liv-in-sky** [comment]
hi zefau,

habe dp gelöscht und adapter installiert

sieht besser aus bis auf:
![Image 4](https://user-images.githubusercontent.com/18462890/67402464-eebe2a00-f5b0-11e9-89ba-eb843b2780ff.png)

**Comment by Zefau** [comment]
@liv-in-sky kannst du das Skript anpassen, dass es als Test integriert werden kann? Also, dass vor dem Release `npm run test` prüft, ob alles passt. Weiterhin wäre eine whitelist klasse, falls einige Datenpunkte gewollt so sind, wie sie sind.
