### ISSUE TITLE
E-Mail addresses with dots

### ISSUE THREAD

**Issue by reloxx13** [Zefau/ioBroker.plex#17]
Heya,

email addresses with (dots) in it are confusing the object lists in iobroker.

e.g. max.mustermann@muster.org

will end in a structure like
plex.0 -> users -> max -> mustermann@muster -> org ->userid

i suggest to just use the userid as object or replace all dots with underscores by creating the objects.

Pi4b debian buster
Node.js: v10.17.0
NPM: 6.12.0
Adapter Version: 0.8.4
JS-Controller:  2.1.1
Admin 3.7.1

**Comment by Zefau** [comment]
Thanks for reporting. Could you try v0.8.5 if that fixes the issue?

**Comment by Zefau** [comment]
@reloxx13

**Comment by reloxx13** [comment]
Heya,

nope, dots are still breaking the tree.

firstname -> lastname@test -> com => no data
real email firstname.lastname@test.com

deleted all plex.0 tree and stopped/started plex instance

**Comment by Zefau** [comment]
Are you running the latest version v0.8.7 ? The email has been replaced by the username now actually, so I'm wondering why this is not applied for you.

https://github.com/Zefau/ioBroker.plex/blob/bc2ab1c1636faf33dd5dd47995ca5f9aba15e4d9/plex.js#L922

**Comment by reloxx13** [comment]
yes.

some users dont have a username. username is not a required field by plex registering form.

**Comment by Zefau** [comment]
Ok, thanks for the info. Please try v0.8.8 as this removes the dots now.

**Comment by reloxx13** [comment]
:(

![grafik](https://user-images.githubusercontent.com/14855001/70334472-c8dda380-1845-11ea-89b8-c38478d5b02d.png)

only one user without email now

**Comment by Zefau** [comment]
Could you try v0.8.9? Thanks

**Comment by Zefau** [comment]
@reloxx13

**Comment by reloxx13** [comment]
Heya,

thank you, it looks fine now!
