### ISSUE TITLE
Allow manual callback ip setting

### ISSUE THREAD

**Issue by dragon299** [Zefau/ioBroker.plex#53]
Webhooks do not work in case iobroker is running within docker. 

I guess the issue is very similar to this one:
https://github.com/Zefau/ioBroker.nuki-extended/issues/51

Could you please check if its the same issue and if it is possible to add a manual callback ip setting?

Thanks.

**Comment by Zefau** [comment]
Sounds reasonable. Will be implemented.

**Comment by Zefau** [comment]
I added an option in the latest version v0.9.0. Please try and install it from Github. Thanks

**Comment by Zefau** [comment]
@dragon299

**Comment by Zefau** [comment]
@dragon299

**Comment by Zefau** [comment]
@dragon299

**Comment by Zefau** [comment]
@dragon299
