### ISSUE TITLE
Media information from current playback

### ISSUE THREAD

**Issue by Mathiasb007** [Zefau/ioBroker.plex#57]
Is it possible to read the media info of the current playback via this adapter. I would be particularly interested in the aspect ratio. Perfect for controlling the canvas masking.

**Comment by Zefau** [comment]
The documentation is very comprehensive and if you're looking through that you will find the answer: yes.

Particularly, with the advanced setup (https://github.com/Zefau/ioBroker.plex/blob/master/README-states.md#with-advanced-setup) using Tautulli that is possible.
